### ISSUE TITLE
FreeIPA container image are now in freeipa/ namespace

### ISSUE THREAD

**Issue by adelton** [keycloak/keycloak-test-docker-images#3]
The

https://github.com/keycloak/keycloak-test-docker-images/blob/master/keycloak-sssd-integration-tests/docker-compose.yml#L4

refers to adelton/freeipa-server:latest.

Please use freeipa/freeipa-server:latest.

**Comment by abstractj** [comment]
See my comment at https://github.com/keycloak/keycloak-test-docker-images/issues/4#issuecomment-303282745
